Repository AY2223S1-CS2103T-T14-1/tp, pull requests merged in 2022-10, with the labels that each got.

#41 Change Person to Internship
  LICENSE
  docs/DeveloperGuide.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/ApplicationStatus.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Internship.java
  src/main/java/seedu/address/model/person/InternshipDate.java
  src/main/java/seedu/address/model/person/InterviewDate.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditInternshipDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/InternshipTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/UniqueInternshipListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#42 Fix checkstyle errors
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/ApplicationStatus.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/InternshipDate.java
  src/main/java/seedu/address/model/person/InterviewDate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation, type.Task

#43 Fix unable to load data
  src/main/java/seedu/address/model/person/ApplicationStatus.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: bug

#44 Add mark command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ApplicationStatus.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, priority.High

#45 Add filter command
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/InternshipHasApplicationStatusPredicate.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, priority.Medium

#48 Update help message
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: enhancement, priority.High

#50 Update User Guide
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/index.md
Labels: documentation, type.Task

#53 Change `AppliedDate` to use `LocalDate`
  docs/UserGuide.md
  src/main/java/seedu/address/model/internship/AppliedDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidInternshipAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/internship/CompanyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: enhancement, priority.Medium

#54 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation, priority.Medium

#55 Fix refactoring errors
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/internship/AppliedDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InternshipListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidInternshipAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditInternshipDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/internship/CompanyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internship/InternshipTest.java
  src/test/java/seedu/address/model/internship/UniqueInternshipListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: enhancement, priority.Medium

#56 Update add command
  docs/UserGuide.md
Labels: documentation, priority.Medium

#57 Add test cases for MarkCommand and MarkCommandParser
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
Labels: enhancement, priority.High

#58 Change AddressBook to FindMyIntern
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: enhancement, priority.Medium

#60 Add test cases for `FilterCommand` and `FilterCommandParser`
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: priority.Medium, type.Task

#72 Allow multiple internship from same company
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/internship/InternshipTest.java
  src/test/java/seedu/address/model/internship/UniqueInternshipListTest.java
Labels: bug, enhancement, priority.High, type.Task

#73 Add filter implementation to DG
  docs/DeveloperGuide.md
  docs/diagrams/FilterCommandActivityDiagram.puml
  docs/images/FilterCommandActivityDiagram.png
Labels: documentation, priority.High, type.Task

#75 Add sort command to DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High, type.Task

#77 Enable assertions
  build.gradle
Labels: priority.Medium, type.Task

#78 Add add command to DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High, type.Task

#80 Add mark command to DG
  docs/DeveloperGuide.md
  docs/diagrams/MarkCommandActivityDiagram.png
  docs/diagrams/MarkCommandActivityDiagram.puml
  docs/images/MarkCommandActivityDiagram.png
  src/main/java/seedu/address/logic/commands/MarkCommand.java
Labels: documentation, priority.High, type.Task

#81 Add feature to allow adding of `interviewDateTime` for internships
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/internship/ApplicationStatus.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/internship/InternshipDate.java
  src/main/java/seedu/address/model/internship/InterviewDate.java
  src/main/java/seedu/address/model/internship/InterviewDateTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/resources/view/InternshipListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidInternshipAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidInternshipAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: enhancement, priority.High, type.Task

#82 Update sample data in `SampleDataUtil`
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Task

#84 Improve GUI
  copyright.txt
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/model/internship/AppliedDate.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/internship/InterviewDateTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/fonts/IBMPlexSans-SemiBold.ttf
  src/main/resources/fonts/IBMPlexSans-Text.ttf
  src/main/resources/images/internship.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/Font.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/InternshipListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: enhancement, priority.High, type.Task

#85 Add sort feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/internship/AppliedDate.java
  src/main/java/seedu/address/model/internship/InterviewDateTime.java
  src/main/java/seedu/address/model/internship/SortCriteria.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/internship/ApplicationStatusTest.java
  src/test/java/seedu/address/model/internship/SortCriteriaTest.java
Labels: enhancement, priority.High, type.Task

#83 Update test cases
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/internship/InterviewDateTime.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditInternshipDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/internship/ApplicationStatusTest.java
  src/test/java/seedu/address/model/internship/InternshipTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: priority.Medium

#87 Display error message on negative index input
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
Labels: bug, priority.Medium

#90 Modify `AddCommandParser` to allow optional `InterviewDateTime`
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: enhancement, priority.Medium

#88 Improve readability and content display
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InternshipListCard.fxml
Labels: enhancement, priority.Medium

#94 Add SortCommand to DG
  docs/DeveloperGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/SortSequenceDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: documentation, priority.High, type.Task

#96 Change Tag to lowercase
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
Labels: bug, priority.High

#98 Resize images
  docs/DeveloperGuide.md
Labels: documentation, priority.High, type.Task

#99 Update `UserGuide.md`
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/findGoogleBackendResult.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/StatusBarFooter.java
Labels: documentation, priority.High, type.Task

#95 Update UI, fix visual bugs
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/InternshipListCard.fxml
Labels: bug, enhancement, priority.Medium

#101 Add Sort Command to UG
  docs/UserGuide.md
Labels: documentation, priority.High, type.Task

#100 Update AddCommand in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/images/AddCommandActivityDiagram.png
Labels: documentation, priority.High, type.Task

#106 Update DG with updated FindCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/findGoogleBackendResult.png
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/internship/InterviewDateTime.java
  src/main/java/seedu/address/model/internship/SortCriteria.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableFindMyIntern.java
  src/test/data/JsonSerializableFindMyInternTest/typicalFindMyIntern.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/testutil/FindMyInternBuilder.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: documentation, priority.High

#108 Update `UserGuide.md`
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/additionalTagsTooltip.png
  docs/images/linkTooltip.png
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: documentation, priority.High, type.Task

#109 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/MarkCommandActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: documentation, priority.High, type.Task

#113 Update site header
  docs/_sass/minima/_base.scss
Labels: documentation, priority.High

#153 Add appendix to `UserGuide.md`
  docs/UserGuide.md
Labels: documentation, priority.Medium

#154 Update user guide
  docs/UserGuide.md
Labels: documentation, priority.Medium

#156 Add styling to UG
  docs/UserGuide.md
Labels: documentation, priority.Medium

#157 Update Table of Content in User Guide
  docs/UserGuide.md
  docs/images/findGoogleBackendResult.png
Labels: documentation, priority.High

#158 Add styling
  docs/UserGuide.md
Labels: documentation, priority.Medium

#160 Fix bugs where internship list reset after edit and mark command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
Labels: bug

#159 Fix table of contents
  docs/UserGuide.md
Labels: documentation, priority.Medium

#162 Update Command section in UG
  docs/UserGuide.md
Labels: documentation, priority.Medium

#163 Add command line guide
  docs/UserGuide.md
  docs/images/CommandLine.png
Labels: documentation, priority.Medium

#165 Fix link validation
  src/main/java/seedu/address/model/internship/Link.java
  src/test/java/seedu/address/model/internship/LinkTest.java
Labels: bug, priority.Medium
