Repository AY2223S1-CS2103T-T14-1/tp, pull requests merged in 2022-11, with the labels that each got.

#169 Update `UserGuide.md`
  docs/UserGuide.md
Labels: bug, documentation, priority.High, type.Task

#168 Update `UserGuide.md`, PPP
  docs/UserGuide.md
  docs/_sass/minima/initialize.scss
  docs/assets/css/style.scss
  docs/images/AnnotatedUi.png
  docs/team/nerbnerb.md
Labels: documentation, priority.Medium, type.Task

#171 Fix `UserGuide` styling
  docs/UserGuide.md
Labels: documentation

#172 Fix grammar
  docs/UserGuide.md
Labels: bug, documentation, priority.High, type.Task

#170 Update Date Parsing
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/internship/AppliedDate.java
  src/main/java/seedu/address/model/internship/InterviewDateTime.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/internship/AppliedDateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
Labels: bug, priority.High, type.Task

#174 Update PPP
  docs/team/marcusgwj.md
Labels: documentation

#173 Update PPP
  docs/team/desmondyst.md
Labels: documentation

#175 Update PPP
  docs/team/puakii.md
Labels: documentation, priority.High

#167 Improve code quality, fix bugs
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/main/java/seedu/address/ui/UiPart.java
Labels: bug, priority.Medium, type.Task

#177 Increase test coverage
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/nerbnerb.md
  src/test/java/seedu/address/logic/parser/FindMyInternParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/internship/AppliedDateTest.java
  src/test/java/seedu/address/model/internship/InterviewDateTimeTest.java
  src/test/java/seedu/address/testutil/TypicalDateTimes.java
Labels: priority.Medium, type.Task

#178 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/marcusgwj.md
  src/main/java/seedu/address/model/internship/AppliedDate.java
  src/main/java/seedu/address/model/internship/InterviewDateTime.java
  src/main/java/seedu/address/model/internship/SortCriteria.java
Labels: documentation, priority.Medium

#179 Resize activity diagram
  docs/DeveloperGuide.md
Labels: documentation

#181 Update `UserGuide.md`, `DeveloperGuide.md`, PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/images/EditCommandActivityDiagram.png
  docs/team/desmondyst.md
Labels: documentation

#183 Update User Guide and PPP
  docs/UserGuide.md
  docs/images/javaVersion.png
  docs/team/puakii.md
Labels: documentation

#188 Fix wrong Tag error message
  docs/UserGuide.md
  src/main/java/seedu/address/model/tag/Tag.java
Labels: bug

#180 Improve code quality, fix bugs
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.Medium

#182 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/FilterSequenceDiagram.png
  docs/team/nerbnerb.md
Labels: documentation, priority.Medium

#192 Update documentation
  docs/UserGuide.md
  docs/team/desmondyst.md
  docs/team/leeianee.md
  docs/team/marcusgwj.md
  docs/team/puakii.md
  src/main/java/seedu/address/model/internship/Link.java
  src/test/java/seedu/address/model/internship/LinkTest.java
Labels: documentation

#194 Fix InterviewDate parsing
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/internship/AppliedDate.java
  src/main/java/seedu/address/model/internship/InterviewDateTime.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/TypicalDateTimes.java
Labels: bug

#195 Add test cases and improve code quality
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/internship/InterviewDateTime.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/model/internship/InterviewDateTimeTest.java
Labels: enhancement, priority.High, type.Task

#198 Enhance code quality and test coverage
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/puakii.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/internship/ApplicationStatus.java
  src/main/java/seedu/address/model/internship/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/model/internship/AppliedDateTest.java
Labels: documentation, enhancement

#199 Update PPP
  docs/team/desmondyst.md
Labels: documentation

#196 Improve code quality
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/internship/ApplicationStatus.java
  src/main/java/seedu/address/model/internship/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/internship/InternshipHasApplicationStatusPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/main/java/seedu/address/ui/InternshipCard.java
  src/test/java/seedu/address/model/internship/AppliedDateTest.java
  src/test/java/seedu/address/model/internship/ContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internship/InternshipHasApplicationStatusPredicateTest.java
  src/test/java/seedu/address/model/internship/InterviewDateTimeTest.java
Labels: priority.Medium

#193 Update documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/css/style.scss
  docs/team/nerbnerb.md
Labels: documentation, priority.High

#200 Improve testing
  docs/AboutUs.md
  src/main/java/seedu/address/model/internship/AppliedDate.java
  src/main/java/seedu/address/model/internship/SortCriteria.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: enhancement, priority.Medium

#201 Update Documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#203 Update user guide
  docs/UserGuide.md
Labels: documentation, priority.Medium

#204 Update Command Line Guide Picture
  docs/UserGuide.md
  docs/images/CommandLine.png
  docs/images/CommandLineGuide.png
Labels: documentation

#205 Update grammar errors in UG
  docs/UserGuide.md
Labels: documentation
